spring:
  mvc:
    static-path-pattern: /public/**

  session:
    jdbc:
      initialize-schema: NEVER

  datasource:
    url: jdbc:mariadb://localhost:3306/identifier
    driver-class-name: org.mariadb.jdbc.Driver
    username: identifier
    password: identifier

  thymeleaf:
    # ?? ?? ??
    prefix: classpath:/templates/
    suffix: .html
#     thymeleaf ?? ??
    enabled: true
    # templates ????? ??? ??? ?? ??
    check-template-location: true

server:
  error:
    whitelabel:
      enabled: false